# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

# 結果のsuggest部分を非表示、最新のCopを自動有効、
AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "**/templates/**/*"
    - "**/vendor/**/*"
    - "app/views/**/*"
    - "config/**/*"
    - "config.ru"
    - "node_modules/**/*"
    - "db/migrate/*"
    - "db/schema.rb"
    - "storage/**/*"
    - "tmp/**/*"
    - "bin/**/*"
    - "Gemfile"

# パフォーマンスルールはテスト配下のファイルを無視するように設定
Performance:
  Exclude:
    - "**/test/**/*"

# 1行の最長の文字数を設定
Layout/LineLength:
  Max: 160

# クラス、モジュール前のドキュメント無しを許可
Style/Documentation:
  Enabled: false

# ASCII以外の文字コメントを許可
Style/AsciiComments:
  Enabled: false

# 文字列リテラルのデフォルトをシングルクォートに設定
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

# メソッドの長さにコメントを含めず、最長行数を設定
Metrics/MethodLength:
  CountComments: false
  Max: 25
  Exclude:
    - test/**/*

# 未使用メソッドの自動修正を無効化
Lint/UnusedMethodArgument:
  AutoCorrect: false

# １つのテストケース内の複数アサーションを許可
RSpec/MultipleExpectations:
  Enabled: false
